motion_adaption_sot:

  wait_for_tf_in_sec:             0.5
  # define the reference frame for the tracked end points of the operator's body
  world_ref_frame_name:           /openni_depth_frame
  # define the tracked end points of the operator's body
  user:
    torso_frame_name:             /torso_1
    head_frame_name:              /head_1
    right_shoulder_frame_name:    /left_shoulder_1
    right_elbow_frame_name:       /left_elbow_1
    right_hand_frame_name:        /left_hand_1
    left_shoulder_frame_name:     /right_shoulder_1
    left_elbow_frame_name:        /right_elbow_1
    left_hand_frame_name:         /right_hand_1
  # define the robot's frames
  robot:
    base_frame_name:              /floor_link
    torso_ref_frame_name:         /torso_1_link
    head_frame_name:              /head_2_link    
    right_shoulder_frame_name:    /arm_right_2_link
    right_elbow_frame_name:       /arm_right_4_link
    right_hand_frame_name:        /arm_right_7_link   
    left_shoulder_frame_name:     /arm_left_2_link
    
  # define roations of orientations by roll pitch yaw
  rotation_angles:
  # align the orientation of the user torso with robot torso
  # i.e.: user bends foward -> ref frame rotates forward
    ref_frame_rot: {p: 0.0, r: 1.5707963267948966, y: -1.5707963267948966}  
  # align adapted frames with goal frames
  goals:
    torso_goal_rot: {p: 1.5707963267948966, r: 3.1415926535897931, y: 0.0}
    head_goal_rot: {p: 1.5707963267948966, r: 3.1415926535897931, y: 0.0}
    right_elbow_goal_rot: {p: 0.0, r: 3.1415926535897931, y: 3.1415926535897931}
    right_hand_goal_rot: {p: 1.5707963267948966, r: 0.0, y: 0.0}
    left_elbow_goal_rot: {p: 3.1415926535897931, r: 0.0, y: 0.0}
    left_hand_goal_rot: {p: -1.5707963267948966, r: 0.0, y: 0.0}
